export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SEARCH_ENTITIES = 'SEARCH_ENTITIES'
export const SEARCH_ASYNC_ENTITIES = 'SEARCH_ASYNC_ENTITIES'
//cargando
export const IS_LOADING = 'IS_LOADING'
//estado inicial
export const ADD_TODO = 'ADD_TODO'
//seccion
export const OPEN_SECCION = 'OPEN_SECCION'
export const CLOSE_SECCION = 'CLOSE_SECCION'
export const SHOW_BOTONERA_ELEGIR_SECCION = 'SHOW_BOTONERA_ELEGIR_SECCION'
export const HIDE_BOTONERA_ELEGIR_SECCION = 'HIDE_BOTONERA_ELEGIR_SECCION'
export const SHOW_SECCION_ELEGITY = 'SHOW_SECCION_ELEGITY'
export const HIDE_SECCION_ELEGITY = 'HIDE_SECCION_ELEGITY'
//alumnos
export const OPEN_FORM_ALUMNO = 'OPEN_FORM_ALUMNO'
export const CLOSE_ALL_ALUMNO = 'CLOSE_FORM_ALUMNO'